[package]
name = "pratt_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc = { git = "https://github.com/Alex-Shand/proc.git" }

[dev-dependencies]
pretty_assertions = "1.4.1"
