[package]
name = "pratt_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc = { git = "https://github.com/Alex-Shand/proc.git" }
proc-macro-crate = "1.3.1"
proc-macro2 = "1.0.64"
quote = "1.0.29"
syn = { version = "2.0.25", features = ["extra-traits", "full"] }
